### ISSUE TITLE
请教下运行时报错：Symbol is not defined 

### ISSUE THREAD

**Issue by atwood-cai** [hax/es6-in-action#1]
hi hax~我安装了依赖包后， 运行报错
es6-in-action/dist/6to5/Router.js:33
var TERMINAL = Symbol("terminal");
               ^
ReferenceError: Symbol is not defined

您遇到了这种问题吗？  能帮忙解决下吗？

**Comment by atwood-cai** [comment]
for...of  =>  for (var _iterator = segments[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {

**Comment by hax** [comment]
用的nodejs的什么版本？试试加 `--harmony` 参数或换用 iojs。

**Comment by atwood-cai** [comment]
多谢 我升级到最新版本没问题了。
